package de.vogella.webservice.java6.first.consumer;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "WiseQuoteServerService", targetNamespace = "http://provider.first.java6.webservice.vogella.de/", wsdlLocation = "http://localhost:9191/wisequotes?wsdl")
public class WiseQuoteServerService extends Service {

	private final static URL WISEQUOTESERVERSERVICE_WSDL_LOCATION;

	static {
		URL url = null;
		try {
			url = new URL("http://localhost:9191/wisequotes?wsdl");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		WISEQUOTESERVERSERVICE_WSDL_LOCATION = url;
	}

	public WiseQuoteServerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WiseQuoteServerService() {
		super(WISEQUOTESERVERSERVICE_WSDL_LOCATION, new QName(
				"http://provider.first.java6.webservice.vogella.de/",
				"WiseQuoteServerService"));
	}

	/**
	 * 
	 * @return returns WiseQuoteServer
	 */
	@WebEndpoint(name = "WiseQuoteServerPort")
	public WiseQuoteServer getWiseQuoteServerPort() {
		return (WiseQuoteServer) super.getPort(new QName(
				"http://provider.first.java6.webservice.vogella.de/",
				"WiseQuoteServerPort"), WiseQuoteServer.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns WiseQuoteServer
	 */
	@WebEndpoint(name = "WiseQuoteServerPort")
	public WiseQuoteServer getWiseQuoteServerPort(WebServiceFeature... features) {
		return (WiseQuoteServer) super.getPort(new QName(
				"http://provider.first.java6.webservice.vogella.de/",
				"WiseQuoteServerPort"), WiseQuoteServer.class, features);
	}

}
